### PR TITLE
Downstream changes for thermostat-16-agent

### PR DESCRIPTION
**Pull request by pkubatrh**
Changes from RHSCL 2.3 release that did not make it into upstream repositories yet.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Seems like the new tests for 16-agent will need some changes to make them work with our CI.

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
The test suite depends on `centos/thermostat-16-storage-centos7` being available somewhere.

**Comment by pkubatrh** [comment]
Some additional failures when running the tests locally:
- centos version of the image does not install nss_wrapper making the tests fail when trying to run the container under a different user
- another builder image is built as part of the tests but is only layered on top of the rhel7 image (no centos variant)
(https://github.com/pkubatrh/thermostat-container/blob/f97932a2bfe5b65ac6ddb42bc89a42a61c95f7a5/16-agent/test/wildfly-builder-image-th-agent/Dockerfile)

**Comment by omron93** [comment]
> another builder image is built as part of the tests but is only layered on top of the rhel7 image (no centos variant)

It makes sense to me to have CentoOS based examples/test-apps on github. 
 - every one can use it and test it
 - rhel variants are run internally before image is released (so it is not so big problem that in github RHEL7 CI a CentOS variant is used)

Another solution would be to make this test "templated" - similar approach is used in PR which adds s2i support to mariadb-container
https://github.com/hhorak/mariadb-container/blob/e609dc6663b03fbe89b9e624b26db549f5e18b25/10.1/test/Dockerfile
https://github.com/sclorg/mariadb-container/pull/32/files#diff-e032f6040f539d497bb5981d5b23c3b5R479

**Comment by pkubatrh** [comment]
>It makes sense to me to have CentoOS based examples/test-apps on github.

Definitely.

>Another solution would be to make this test "templated" - similar approach is used in PR which adds s2i support to mariadb-container

I think we will need to make it "templatable" anyway, since with our CI the tested image is tagged as *-candidate while the Dockerfile would need to be layered upon non-candidate build in order to not fail on rhel.

**Comment by omron93** [comment]
@pkubatrh I think rebase is needed.

>I think we will need to make it "templatable" anyway, since with our CI the tested image is tagged as *-candidate while the Dockerfile would need to be layered upon non-candidate build in order to not fail on rhel.

You are right.

**Comment by pkubatrh** [comment]
Rebased, tests are green.

The test suite still relies on `centos/thermostat-16-storage-centos7` being available however. It might make more sense to use the *-candidate build instead, as it is built before the test case using it is started  anyway.

**Comment by omron93** [comment]
LGTM, @pkubatrh Thank you. Merging.

**Pull request merged**
