### PR TITLE
Downstream changes for thermostat-16-storage

### PR DESCRIPTION
**Pull request by pkubatrh**
Changes from RHSCL 2.3 release that did not make it into upstream repositories yet.

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by pkubatrh** [comment]
Looking at the test results it seems like only the (EOL) 1-agent image is being built as part of the PR CI...

**Comment by omron93** [comment]
That is right.
@pkubatrh Could you update please `VERSIONS = ...` in `Makefile` in this PR please?

Not sure that it was omitted intentionally when new thermostat version was added (missing CentOS/RHEL builds) ... Definitely you are right that it is a bug now.

**Comment by pkubatrh** [comment]
Ah right, I have missed that VERSIONS is not set properly, thanks.

**Comment by omron93** [comment]
It seems clear now why it was not added :-) New versions were not built in CentOS yet. That is why CentOS CI is failing.

Anyway, it LGTM and RHEL CI is passing. Thank you.

I can prepare CentOS Dockerfile next week to make tests passing. So I would wait until that with this PR - thermostat container doesn't have so much PRs, so it won't make a lot of troubles I hope.

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
@pkubatrh Please rebase and apply relevant changes also to CentOS Dockerfiles. Thanks.

Testing should work now.

**Comment by pkubatrh** [comment]
Rebased and Dockerfiles synced.

**Comment by omron93** [comment]
Thanks.

Tests are same for RHEL and CentOS. But there is `MONGODB_IMAGE=${MONGODB_IMAGE:-rhscl/mongodb-32-rhel7}` and `rhscl` images are not present in CentOS (subscription is needed). @pkubatrh Could you update this please to use `centos/mongodb-32-centos7` in CentOS?

**Comment by pkubatrh** [comment]
Ah right, I forgot the tests are written with rhel images in mind. Although I think the best approach would be to just set the MONGODB_IMAGE environment variable to the centos image inside the centos CI. Is it possible to do that @omron93 ?

**Comment by pkubatrh** [comment]
Although the default values should still be centos7 based images...

I guess this will make the tests pass even on rhel7 but Im not sure whether it is ok to use centos versions of other images while testing a rhel based image...

**Comment by omron93** [comment]
> Although I think the best approach would be to just set the MONGODB_IMAGE environment variable to the centos image inside the centos CI. Is it possible to do that @omron93 ?

It is possible, but I would like to avoid this. Currently CI jobs for all images are same and it makes maintenance easier.

@pkubatrh What about `MONGODB_IMAGE=$(echo $IMAGE_NAME | sed "s|thermostat-${VERSION//./}|mongodb-32|")` ?

**Comment by pkubatrh** [comment]
>It is possible, but I would like to avoid this. Currently CI jobs for all images are same and it makes maintenance easier.

Right, I was just wondering how much of a pain it would be to leave it to CI given the code in tests is already prepared to use different images.

Will try to work out something that could be used without needing to change CI.

**Comment by pkubatrh** [comment]
@omron93 I have modified the test suite based on your suggestion. Please take a look

**Comment by omron93** [comment]
LGTM, thank you. @pkubatrh Anything to add/merge or I can merge it?

**Comment by pkubatrh** [comment]
Should be ready to merge now.

**Pull request merged**
